<section class="container">
    <ol class="treemap static">
        <li class="active"><a href="<?php echo $this->basePath() ?>">Inicio</a></li>
        <li class="active"><a href="<?php echo $this->basePath('carrito') ?>">Carrito</a></li>
    </ol>
    <h1 class="page-header">Canje exitoso.</h1>

    <div class="jumbotron">
        <center>
            <h2>Tu número de referencia es:</h2>
            <h1><?php echo $this->paramsOrder['order']; ?></h1>
        </center>
        <ul class="list-group">
            <li class="list-group-item"> <h3>Nombre: <small><?php echo $this->paramsOrder['usename']; ?></small></h3></li>
            <li class="list-group-item"><h3>Email: <small><?php echo $this->user['email'] ?></small></h3></li>
            <li class="list-group-item"><h3>Fecha de canje: <small><?php echo date('m-d-Y',$this->paramsOrder['date'])  ?></small></h3></li>

        </ul>
        <div class="table-responsive">                   
            <table class="table table-striped">
                <thead>
                    <tr>

                        <th>Foto</th>
                        <th>Producto</th>
                        <th>Código</th>
                        <th>Precio</th>
                        <th>Cantidad</th>

                    </tr>
                </thead>
                <tbody>
                     <?php foreach ($this->paramsOrder['allCart'] as $item) : ?>                  
                    <tr>
                        <td class="minicat"><img src="<?php echo $this->basePath('assets/img/product/' . $item['sku'].'.jpg'); ?>"></td>
                        <td><?php echo $item['other_sku']; ?></td>
                        <td><?php echo $item['sku']; ?></td>
                        <td><?php echo number_format(((float) $item['price']), 0, '.', ','); ?></td>
                        <td><?php echo $item['quantity']; ?></td>
                    </tr>  
                    <?php endforeach; ?>   
                   
                </tbody>
            </table></div>
        <center><div class="alert alert-danger">Tu número de referencia es la clave para cualquier aclaración, imprímelo.</div></center>
        <div align="right">

            <a class="btn btn-success btn-large" href="<?php echo $this->basePath(); ?>">Terminar</a> 
            <a class="btn btn-info btn-large" href="#" onclick="javascript:window.print();">Imprimir</a>  
            <br><br></div>


    </div>


    <br>

    <div class="jumbotron">
        <center>
            <p>Síguenos en nuestras redes sociales.</p>
            <a href="#about"><img src="assets/img/fbk.png"></a>&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="#contact"><img src="assets/img/twi.png"></a><br>

            <a href="#about">Instrucciones para la APP</a>&nbsp;&nbsp; | &nbsp;&nbsp;
            <a href="#contact">Términos y condiciones</a>
        </center>
    </div>

</section>