<ul id="side-menu" class="nav">
	<li>
        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <li>
                <a href="flot.html">Flot Charts</a>
            </li>
            <li>
                <a href="morris.html">Morris.js Charts</a>
            </li>
        </ul>
        <!-- /.nav-second-level -->
    </li>
<?php foreach ($this->container as $page): ?>
    <li <?= $page->isActive()? 'class="active"' : '' ?>>
        <?= $this->navigation()->menu()->htmlify($page);?>
        <ul class="nav nav-second-level">
            <li>
                <a href="flot.html">Flot Charts</a>
            </li>
            <li>
                <a href="morris.html">Morris.js Charts</a>
            </li>
        </ul>
    </li>
<?php endforeach; ?>
</ul>