<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Programa'); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headMeta()->appendName('description', 'Concurso de Autoservicio') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/ico/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.css')
                ->prependStylesheet($this->basePath() . '/assets/css/navbar.css')
                ->prependStylesheet($this->basePath() . '/assets/css/carousel.css')
                ->prependStylesheet($this->basePath() . '/css/nav_bar.css')
                ->prependStylesheet($this->basePath() . '/css/app.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/assets/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/assets/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/assets/js/jquery.steps.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.js')
        ?>
        <script src="<?php echo $this->basePath('js/nav_bar.js') ?>"></script>
        <style> 
            @font-face
            {
                font-family: "bebasneue";
                src: url("<?php echo $this->basePath() ?>/assets/fonts/BebasNeue.otf") format("opentype");
                src: url("<?php echo $this->basePath() ?>/assets/fonts/BebasNeue.eot?#bebasneue") format("embedded-opentype"),
                    url("<?php echo $this->basePath() ?>/assets/fonts/BebasNeue.woff") format("woff"),
                    url("<?php echo $this->basePath() ?>/assets/fonts/BebasNeue.ttf") format("truetype");
            }

        </style>        

    </head>
    <body style="padding:0px;">
        <header style="padding-top:30px; margin-bottom: -20px">
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div>
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href=""></a>
                    </div>
                    <?php if (!empty($this->barUser['displayName'])): ?>
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="active"><a href="#"><span style="color:#999999"><b>Bienvenido(a):</b> <?php echo $this->barUser['displayName']; ?> </span><span class="glyphicon glyphicon-heart-empty"></span>&nbsp;<b><?php echo $this->barCredit['credit']; ?> pts.</b></a></li>
                                <li ><a href="<?php echo $this->url('cshelperzfcuser/logout') ?>">Cerrar sesión</a></li>
                            </ul>
                        </div><!--/.nav-collapse -->        
                    <?php else: ?>
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav navbar-right">              
                                <li ><a href="<?php echo $this->url('cshelperzfcuser/login') ?>">Iniciar sesión</a></li>        
                            </ul>
                        </div><!--/.nav-collapse -->            
                    <?php endif; ?>
                </div>
            </div>
            <br>
            <div class="container" >
                <div id="header2">
                    <a href="<?php echo $this->basePath() ?>"> <img id="logo" src="<?php echo $this->basePath() ?>/assets/img/logo.png"></a></div>
                <!-- Static navbar -->
                <div id="header3">
                    <div class="navbar navbar-default">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand active" href="<?php echo $this->basePath() ?>">Inicio</a>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li class="dropdown">
                                    <a href="mecanica.html" class="dropdown-toggle" data-toggle="dropdown">Mecánica<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->basePath('mecanica') ?>">Mecánica ADPRESS</a></li>
                                        <?php if (isset($this->barUser['displayName'])): ?>
                                            <li class="divider"></li>
                                            <li><a href="<?php echo $this->basePath('promociones') ?>">Promociones</a></li>
                                            <li class="divider"></li>
                                            <li><a href="<?php echo $this->basePath('apps') ?>">Descarga de APPS</a></li>
                                        <?php endif; ?>
                                    </ul>
                                </li>
                                <?php if (!isset($this->barUser['displayName'])): ?>
                                 <li class="">
                                    <a href="<?php echo $this->basePath('usuarios/activate') ?>">Activa tu cuenta</a>
                                </li>
                                <?php endif; ?>
                                <?php if (isset($this->barUser['displayName'])): ?>
                                    <li><a href="<?php echo $this->basePath() . '/usuarios/miperfil' ?>">Mi perfil</a></li>
                                    <li><a href="<?php echo $this->basePath() . '/categories' ?>">Catálogo</a></li>
                                    <li><a href="<?php echo $this->basePath('carrito') ?>">Carrito</a></li>             
                                    <li class="dropdown">
                                        <a href="<?php echo $this->basePath('micuenta') ?>" class="dropdown-toggle" data-toggle="dropdown">Estado de Cuenta<b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="<?php echo $this->basePath('micuenta') ?>">Mi Cuenta</a></li>
                                            <li class="divider"></li>
                                            <li><a href="<?php echo $this->basePath('pedidos') ?>">Historial de Pedidos</a></li>
                                        </ul>
                                    </li>
                                <?php endif; ?>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li class="active"><a href="<?php echo $this->basePath('ayuda') ?>"><span class="glyphicon glyphicon-question-sign"></span></a></li>
                            </ul>
                        </div><!--/.nav-collapse -->

                    </div></div></div> 
            <ol class="breadcrumb container" id="oculto">
                <?php
                $navigation = $this->navigation('Navigation')->menu();
                $navigation->setUlClass('treemap');
                ?>
                <?php
                echo $navigation->render(
                        null, array(
                    'minDepth' => 2,
                    'maxDepth' => 2,
                    'onlyActiveBranch' => true,
                    'renderParents' => false,
                    'renderChilds' => false,
                    'onlyActiveBranch' => true
                ));
                ?>
            </ol>
        </header>
<?php echo $this->content; ?>      
        <div id="footer" class="navbar-fixed-bottom" style="padding:0px; background-color: #101010;">
            <div>
                <div style="width: 760px;margin: 0 auto;">
                    <div>
                        
                    </div>
                    <div style="clear: both"></div>
                    <center> 
                        <div style="font-size:10px; width:97%;color:#fff;margin-top: 10px;">
                            © Copyleft 2014. Proyecto CookieShop <a href="https://github.com/CookieShop/Shopsimple">en github</a> <b>
                                
                            </b>
                        </div>
                        <a href="<?php echo $this->basePath('aviso') ?>" style="color:#FFF;">Aviso de Privacidad</a>
                    </center>
                </div>
            </div>
        </div>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="<?php echo $this->basePath() ?>/assets/js/jquery.js"></script>
        <script src="<?php echo $this->basePath() ?>/assets/js/bootstrap.min.js"></script>        
    </body>
</html>
