<?= $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Base App'); ?>
        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?= $this->headMeta()->appendName('description', 'Base app') ?>
        <?= $this->headLink(
                array(
                    'rel' => 'shortcut icon', 
                    'type' => 'image/vnd.microsoft.icon', 
                    'href' => $this->basePath() . '/assets/ico/favicon.ico')
                )
                ->prependStylesheet($this->basePath() . '/assets/font-awesome-4.1.0/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/plugins/morris.css')
                ->prependStylesheet($this->basePath() . '/assets/css/sb-admin-2.css')
                ->prependStylesheet($this->basePath() . '/assets/css/plugins/timeline.css')
                ->prependStylesheet($this->basePath() . '/assets/css/plugins/metisMenu/metisMenu.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css');
        ?>
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div id="wrapper">
            <!-- Navigation -->
            <header>
                <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="index.html">Base App</a>
                    </div>
                    <!-- /.navbar-header -->
                    <ul class="nav navbar-top-links navbar-right">

                    <?php if (!empty($this->barUser['displayName'])): ?>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-heart"></i> 
                                <?= $this->barCredit['credit'];?> puntos disponibles&nbsp;
                                <i class="fa fa-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?php echo $this->basePath() . '/categories' ?>">
                                        <i class="fa fa-book"></i> Catálogo
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->basePath('carrito') ?>">
                                        <i class="fa fa-shopping-cart"></i> Carrito
                                    </a>
                                </li> 
                                <li>
                                    <a href="<?php echo $this->basePath('micuenta') ?>">
                                        <i class="fa fa-credit-card"></i> Mi Cuenta
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->basePath('pedidos') ?>">
                                        <i class="fa fa-list-alt"></i> Historial de Pedidos
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php echo $this->basePath('ayuda') ?>">
                                        <i class="fa fa-life-ring"></i> Ayuda</a>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-user fa-fw"></i> 
                                <?= $this->barUser['displayName'];?> 
                                <i class="fa fa-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li>
                                    <a href="<?php echo $this->basePath() . '/usuarios/miperfil' ?>">
                                        <i class="fa fa-user fa-fw"></i>  Mi perfil
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->basePath('usuarios/activate') ?>">
                                        <i class="fa fa-gear fa-fw"></i> Activa tu cuenta
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php echo $this->url('cshelperzfcuser/logout') ?>">
                                        <i class="fa fa-sign-out fa-fw"></i> Logout
                                    </a>
                                </li>
                            </ul>
                        </li>
                    <?php else: ?>
                        <li class="dropdown">
                            <a class="dropdown-toggle" href="<?php echo $this->basePath('ayuda') ?>">
                                <i class="fa fa-sign-in"></i> Login
                            </a>
                        </li>
                    <?php endif; ?>
                    </ul>
                    <div class="navbar-default sidebar" role="navigation">
                        <div class="sidebar-nav navbar-collapse">
                            <?= $this->navigation('navigation')
                                    ->menu()
                                    ->setPartial('partials/menu')->render();
                            ?>
                        </div>
                    </div>
                </nav>
            </header>
            <div id="page-wrapper">
                <?= $this->content;?>
            </div>
        </div>    
        <footer class="navbar-fixed-bottom">
            <div>
                &copy; 2014. Zend Framework 2 - Skeleton Application 
                <a href="https://github.com/soberanes/zf2-skeleton"><i class="fa fa-github"></i></a>
            </div>
        </footer>
        <?php echo $this->headScript()
                ->prependFile($this->basePath() . '/assets/js/sb-admin-2.js')
                ->prependFile($this->basePath() . '/assets/js/plugins/metisMenu/metisMenu.min.js')  
                ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery-1.11.0.js') ?>
    </body>
</html>
