<?= $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Base App'); ?>
        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?= $this->headMeta()->appendName('description', 'Base app') ?>
        <?= $this->headLink(
                array(
                    'rel' => 'shortcut icon', 
                    'type' => 'image/vnd.microsoft.icon', 
                    'href' => $this->basePath() . '/assets/ico/favicon.ico')
                )
                ->prependStylesheet($this->basePath() . '/assets/font-awesome-4.1.0/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/plugins/morris.css')
                ->prependStylesheet($this->basePath() . '/assets/css/sb-admin-2.css')
                ->prependStylesheet($this->basePath() . '/assets/css/plugins/timeline.css')
                ->prependStylesheet($this->basePath() . '/assets/css/plugins/metisMenu/metisMenu.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css');
        ?>
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div id="wrapper">
            <!-- Navigation -->
            <header>
                <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="index.html">Base App</a>
                    </div>
                    <!-- /.navbar-header -->
                    <ul class="nav navbar-top-links navbar-right">

                    </ul>
                    <?php if (!empty($this->barUser['displayName'])): ?>
                        <li class="active">
                            <a href="#">
                                <span style="color:#999999"><b>Welcome:</b> <?php echo $this->barUser['displayName']; ?> </span>
                                <span class="glyphicon glyphicon-heart-empty"></span>&nbsp;
                                <b><?php echo $this->barCredit['credit']; ?> pts.</b>
                            </a>
                        </li>
                    <?php else: ?>

                    <?php endif; ?>
                </nav>
            </header>
        </div>


        <header style="padding-top:30px; margin-bottom: -20px">
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div>
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href=""></a>
                    </div>
                    <?php if (!empty($this->barUser['displayName'])): ?>
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="active">
                                    <a href="#">
                                        <span style="color:#999999"><b>Bienvenido(a):</b> <?php echo $this->barUser['displayName']; ?> </span>
                                        <span class="glyphicon glyphicon-heart-empty"></span>&nbsp;
                                        <b><?php echo $this->barCredit['credit']; ?> pts.</b>
                                    </a>
                                </li>
                                <li ><a href="<?php echo $this->url('cshelperzfcuser/logout') ?>">Cerrar sesión</a></li>
                            </ul>
                        </div><!--/.nav-collapse -->        
                    <?php else: ?>
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav navbar-right">              
                                <li ><a href="<?php echo $this->url('cshelperzfcuser/login') ?>">Iniciar sesión</a></li>        
                            </ul>
                        </div><!--/.nav-collapse -->            
                    <?php endif; ?>
                </div>
            </div>
            <br>
            <div class="container" >
                <div id="header2">
                    <a href="<?php echo $this->basePath() ?>"> <img id="logo" src="<?php echo $this->basePath() ?>/assets/img/logo.png"></a></div>
                <!-- Static navbar -->
                <div id="header3">
                    <div class="navbar navbar-default">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand active" href="<?php echo $this->basePath() ?>">Inicio</a>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li class="dropdown">
                                    <a href="mecanica.html" class="dropdown-toggle" data-toggle="dropdown">Mecánica<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->basePath('mecanica') ?>">Mecánica ADPRESS</a></li>
                                        <?php if (isset($this->barUser['displayName'])): ?>
                                            <li class="divider"></li>
                                            <li><a href="<?php echo $this->basePath('promociones') ?>">Promociones</a></li>
                                            <li class="divider"></li>
                                            <li><a href="<?php echo $this->basePath('apps') ?>">Descarga de APPS</a></li>
                                        <?php endif; ?>
                                    </ul>
                                </li>
                                <?php if (!isset($this->barUser['displayName'])): ?>
                                 <li class="">
                                    <a href="<?php echo $this->basePath('usuarios/activate') ?>">Activa tu cuenta</a>
                                </li>
                                <?php endif; ?>
                                <?php if (isset($this->barUser['displayName'])): ?>
                                    <li><a href="<?php echo $this->basePath() . '/usuarios/miperfil' ?>">Mi perfil</a></li>
                                    <li><a href="<?php echo $this->basePath() . '/categories' ?>">Catálogo</a></li>
                                    <li><a href="<?php echo $this->basePath('carrito') ?>">Carrito</a></li>             
                                    <li class="dropdown">
                                        <a href="<?php echo $this->basePath('micuenta') ?>" class="dropdown-toggle" data-toggle="dropdown">Estado de Cuenta<b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="<?php echo $this->basePath('micuenta') ?>">Mi Cuenta</a></li>
                                            <li class="divider"></li>
                                            <li><a href="<?php echo $this->basePath('pedidos') ?>">Historial de Pedidos</a></li>
                                        </ul>
                                    </li>
                                <?php endif; ?>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li class="active"><a href="<?php echo $this->basePath('ayuda') ?>"><span class="glyphicon glyphicon-question-sign"></span></a></li>
                            </ul>
                        </div><!--/.nav-collapse -->

                    </div></div></div> 
            <ol class="breadcrumb container" id="oculto">
                <?php
                $navigation = $this->navigation('Navigation')->menu();
                $navigation->setUlClass('treemap');
                ?>
                <?php
                echo $navigation->render(
                        null, array(
                    'minDepth' => 2,
                    'maxDepth' => 2,
                    'onlyActiveBranch' => true,
                    'renderParents' => false,
                    'renderChilds' => false,
                    'onlyActiveBranch' => true
                ));
                ?>
            </ol>
        </header>
            <?php echo $this->content; ?>      
        <footer class="navbar-fixed-bottom">
            <div>
                &copy; 2014. Zend Framework 2 - Skeleton Application 
                <a href="https://github.com/soberanes/zf2-skeleton"><i class="fa fa-github"></i></a>
            </div>
        </footer>
        <?php echo $this->headScript()
                ->prependFile($this->basePath() . '/assets/js/sb-admin-2.js')
                ->prependFile($this->basePath() . '/assets/js/plugins/metisMenu/metisMenu.min.js')  
                ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery-1.11.0.js') ?>
    </body>
</html>
