<?= $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Base App'); ?>
        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?= $this->headMeta()->appendName('description', 'Base app') ?>
        <?= $this->headLink(
                array(
                    'rel' => 'shortcut icon', 
                    'type' => 'image/vnd.microsoft.icon', 
                    'href' => $this->basePath() . '/assets/ico/favicon.ico')
                )
                ->prependStylesheet($this->basePath() . '/assets/font-awesome-4.1.0/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/sb-admin-2.css')
                ->prependStylesheet($this->basePath() . '/assets/css/plugins/metisMenu/metisMenu.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css');
        ?>
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
	</head>
    <body>
        <section class="container">
            <?= $this->content; ?>
        </section>
        <footer class="navbar-fixed-bottom">
            <div>
                &copy; 2014. Zend Framework 2 - Skeleton Application 
                <a href="https://github.com/soberanes/zf2-skeleton"><i class="fa fa-github"></i></a>
            </div>
        </footer>
        <?= $this->headScript()
                ->prependFile($this->basePath() . '/assets/js/sb-admin-2.js')
                ->prependFile($this->basePath() . '/assets/js/plugins/metisMenu/metisMenu.min.js')  
                ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery-1.11.0.js') ?>
    </body>
</html>

