<?php 
$this->layout()->setTemplate('cshelperzfcuser/user/layout.phtml');
$this->layout()->setTerminal(true);
?>
<section class="headeri" style="margin:auto; margin-top:10em;color:#727272">
     <div class="headeri">
         <div class="col-lg-6 col-md-6 hero-feature" style="padding-right:4em;">
         <img id="logo2" src="<?php echo $this->basePath()?>/assets/img/logo.png">
         <br><br>
             <h1 style="font-family: bebasneue;">¡Descubre el mundo de recompensas que tenemos para tí!</h1>
             
             <?php if ($this->enableRegistration) : ?>
             <h2 style="font-family: bebasneue;">
            Not registered? <a href="<?php echo $this->url('cshelperzfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">registrate aquí</a></h2>
            <?php endif; ?>
         </div>
     <div class="col-lg-6 col-md-6 hero-feature">
         <br>
         <div style="float:right;font-size: 30px;"> <a href="#"><span class="glyphicon glyphicon-question-sign"></span></a></div>
         <div style="clear: both"></div>
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('cshelperzfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-signin');
$form->get('identity')->setAttribute('class', 'form-control');
$form->get('identity')->setAttribute('placeholder', 'Correo electrónico');
$form->get('identity')->setAttribute('autofocus', '');
$form->get('credential')->setAttribute('class', 'form-control');
$form->get('credential')->setAttribute('placeholder', 'Contraseña');
$form->get('credential')->setAttribute('autocomplete', 'off');
$form->get('submit')->setAttribute('class', 'btn btn-lg btn-primary btn-block');
$form->get('submit')->setLabel('Entrar');
?>         
         <?php echo $this->form()->openTag($form) ?>
        <h2 class="form-signin-heading">Iniciar Sesión</h2>
        <?php echo $this->formInput($form->get('identity')) ?>
        <br>
        <?php echo $this->formInput($form->get('credential')) ?>
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Recordar mis datos
        </label>
        <?php echo $this->formHidden($form->get('csrf')) ?>
        <?php echo $this->formButton($form->get('submit')) ?>
      <!--<button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>-->
        <center><h4>¿Olvidaste tu contraseña?</h4></center>
        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>        
      <?php echo $this->form()->closeTag() ?>
         </div>
    </div>
   </section>
