<section class="container">
    <h2 class="page-header">Mi Perfil</h2>
    <div class="jumbotron">
        <?php if(!is_null($this->susses)):?>
        <center><div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><?php echo ' '.$this->susses; ?></div></center>
        <?php endif;?>        
        <?php if(!is_null($this->message)):?>
        <center><div class="alert alert-danger"><span class="glyphicon glyphicon-ban-circle"></span><?php echo ' '.$this->message; ?></div></center>
        <?php endif;?>
        <?php $form = $this->formMiPerfil;
        $form->setAttribute('action',$this->basePath('usuarios/miperfil'));
        ?>
        <?php echo $this->form()->openTag($form) ?>
            <div class="form-group">
                <label for="username">Usuario</label>
                <?php echo $this->formInput($form->get('username')) ?>
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <?php echo $this->formInput($form->get('email')) ?>
            </div> 
            <div class="form-group">
                <label for="displayname">Nombre</label>
                <?php echo $this->formInput($form->get('displayname')) ?>
            </div>       
            <div class="form-group">
                <label for="passwordactual">Contraseña actual</label>
                <?php echo $this->formInput($form->get('passwordactual')) ?>
            </div>         
            <div class="form-group">
                <label for="passwordnew">Contraseña nueva</label>
                <?php echo $this->formInput($form->get('passwordnew')) ?>
            </div>  
            <div class="form-group">
                <label for="passwordnewverify">Confirmar contraseña</label>
                <?php echo $this->formInput($form->get('passwordnewverify')) ?>
            </div>
            <?php echo $this->formHidden($form->get('csrf')) ?>
        <?php echo $this->formSubmit($form->get('btn_miperfil')) ?>
        <?php echo $this->form()->closeTag() ?> 
         
    </div>    

    <br>
    <div class="jumbotron">
        <center>
            <p>Síguenos en nuestras redes sociales.</p>
            <a href=""><img src="<?php echo $this->basePath() ?>/assets/img/fbk.png"></a>&nbsp;&nbsp;&nbsp;&nbsp;
            <a href=""><img src="<?php echo $this->basePath() ?>/assets/img/twi.png"></a><br>

            <a href="">Instrucciones para la APP</a>&nbsp;&nbsp; | &nbsp;&nbsp;
            <a href="">Términos y condiciones</a>
        </center>
    </div>
</section> <!-- /container -->
