<section class="container">
    <h1 class="page-header">Historial de pedidos. <small>Aquí puedes revisar tu historial de pedidos.</small></h1>
    <div class="jumbotron">
        <center>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Pedido</th>
                        <th>Cantidad</th>
                        <th>Fecha</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->paginator as $pedido): ?>
                        <tr>
                            <td><?php echo $pedido['id'] ?></td>
                            <td><?php echo $pedido['articulo']['other_sku'] ?></td>
                            <td><?php echo $pedido['cantidad']?></td>
                            <td><?php echo date('d/m/Y', $pedido['order_date']) ?></td>
                        </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
             <?php // add at the end of the file after the table
            echo $this->paginationControl(
                // the paginator object
                $this->paginator,
                // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                'sliding',
                // the partial to use to render the control
                array('partial/paginator.phtml', 'EstadoCuenta'),
                // the route to link to when a user clicks a control link
                array(
                    'route' => 'pedidos'
                )
            );
            ?>
        </center>
    </div>


    <br>

    <div class="jumbotron">
        <center>
            <p>Síguenos en nuestras redes sociales.</p>
            <a href="#about"><img src="assets/img/fbk.png"></a>&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="#contact"><img src="assets/img/twi.png"></a><br>

            <a href="#about">Instrucciones para la APP</a>&nbsp;&nbsp; | &nbsp;&nbsp;
            <a href="#contact">Términos y condiciones</a>
        </center>
    </div>
</section> <!-- /container -->