<?php $row = $this->producto; ?>
<section>
    <div class="container">
        <ul class="treemap static">
            <li class="active"><a href="<?php echo $this->basePath() ?>">Inicio</a></li>
            <li class="active"><a href="<?php echo $this->basePath('categories') ?>">Catálogo</a></li>
            <li class="active"><a href="<?php  echo $this->basePath('productsc/'.$this->cetegoria['id'])?>"><?php echo $this->cetegoria['name'] ?></a></li>
            <li class="active"><a href="#"><?php echo $row['other_sku']; ?></a></li>
        </ul>

        <div class="row jumbotron">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $row['other_sku']; ?>
                        <small>
                            <span class="glyphicon glyphicon-heart-empty"></span><?php echo $row['price']; ?><b><?php echo $row['currency']; ?></b>
                        </small>
                        <div style="float:right" type="button" class="btn btn-default"><a style="text-decoration: none;" href="<?php echo $this->basePath('productsc/'.$this->cetegoria['id'].'/1') ?>">Regresar</a></div></h1>
                </div>
            </div>

            <div class="row">
                <div class="col-md-8">
                    <img class="img-responsive" 
                         src="<?php
                         echo $this->basePath('assets/img/product/' .
                                 $row['full_image']);
                         ?>">
                </div>

                <div class="col-md-4">
                    <h3>Código:<b><?php echo $row['sku']; ?></b></h3>
                    <h3>Descripción del producto:</h3>
                    <p><?php echo $row['description']; ?></p>
                    <p><center>
                        <?php $form = $this->form ?>
                        <?php $form->setAttribute('action', $this->basePath('carrito/2')); ?>
                        <?php echo $this->form()->openTag($form) ?>
                        <?php echo $this->formSelect($form->get('quantity')) ?>

                        <?php $form->get('product_id')->setValue($row['id']) ?>
                        <?php echo $this->formHidden($form->get('product_id')) ?>

                        <?php $form->get('user_id')->setValue($this->user['id']) ?>
                        <?php echo $this->formHidden($form->get('user_id')) ?>

                        <?php $form->get('price')->setValue($row['price']) ?>
                        <?php echo $this->formHidden($form->get('price')) ?>

                        <?php echo $this->formHidden($form->get('csrf')) ?>

                        <?php echo $this->formSubmit($form->get('submit')) ?>

<?php echo $this->form()->closeTag() ?>                   

                        </p>

                        <div class="alert alert-warning" style="font-family: arial; font-size: 14px;">   <p>En caso de que no se tuviera en existencia el artículo seleccionado, se enviará un artículo sustituto el cual se ajustará a las características del premio elegido.</p>
                        </div>
                </div>
            </div>
        </div>



    </div>
</section> <!-- /container -->
<style>
     .breadcrumb{
        margin-top: -50px;
    }
</style>
