      <section  class="container">
          <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" >
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" >
        <div class="item active">
          <img src="<?php echo $this->basePath()?>/assets/img/hap2.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:First slide" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>¡Bienvenido al Club!</h1>
              <p>Descubre aquí lo que puedes lograr con tus compras.</p>
              <p>No debes perder esta oportunidad.</p>
              <p><a class="btn btn-large btn-primary" href="<?php echo $this->basePath('usuarios/login') ?>">Entrar</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="<?php echo $this->basePath()?>/assets/img/hap3.jpg" data-src="/holder.js/100%x500/auto/#777:#7a7a7a/text:Second slide" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
                 <h1 style="color:#000">¡Bienvenido al Club!</h1>
              <p style="color:#000">Descubre aquí lo que puedes lograr con tus compras.</p>
              <p style="color:#000">No debes perder esta oportunidad.</p>
      
              <p><a class="btn btn-large btn-primary" href="<?php echo $this->basePath('usuarios/login') ?>">Entrar</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="<?php echo $this->basePath()?>/assets/img/hap4.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Third slide" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
             <h1>¡Bienvenido al Club!</h1>
              <p>Descubre aquí lo que puedes lograr con tus compras.</p>
              <p>No debes perder esta oportunidad.</p>
              <p><a class="btn btn-large btn-primary" href="<?php echo $this->basePath('usuarios/login') ?>">Entrar</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->
     <!-- Main component for a primary marketing message or call to action -->
     
     <div class="row text-center">

        <div class="col-lg-6 col-md-6 hero-feature">
          <div class="thumbnail">
            <img src="<?php echo $this->basePath()?>/assets/img/androidapp.png" alt="">
            <div class="caption">
                       <p>Obtén la nueva versión para android.</p>
              <p><a href="#" class="btn btn-primary">Descarga</a> <a href="#" class="btn btn-default">Tutorial</a></p>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-md-6 hero-feature">
          <div class="thumbnail">
            <img src="<?php echo $this->basePath()?>/assets/img/iosapp.png" alt="">
            <div class="caption">
                       <p>Obtén la nueva versión para IOS.</p>
              <p><a href="#" class="btn btn-primary">Descarga</a> <a href="#" class="btn btn-default">Tutorial</a></p>
            </div>
          </div>
        </div>

      </div>
     
     
     <br>
     
      <div class="jumbotron">
          <center>
        <p>Síguenos en nuestras redes sociales.</p>
          <a href="#about"><img src="<?php echo $this->basePath()?>/assets/img/fbk.png"></a>&nbsp;&nbsp;&nbsp;&nbsp;
           <a href="#contact"><img src="<?php echo $this->basePath()?>/assets/img/twi.png"></a><br>
           
        <a href="#about">Instrucciones para la APP</a>&nbsp;&nbsp; | &nbsp;&nbsp;
           <a href="#contact">Términos y condiciones</a>
          </center>
      </div>

      </section> <!-- /container -->