<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */

namespace Cspermission\Model;
                  
use Zend\Db\Adapter\Adapter;
use Zend\Db\TableGateway\AbstractTableGateway;
use Zend\Db\Sql\Select as Select;
use Cspermission\Model\Entity\Resource as Resource;
                    
class ResourceTable extends AbstractTableGateway{
   
    protected $table  = 'resource';
    
    public function __construct(Adapter $adapter) {
        $this->adapter = $adapter;
    }
    
    public function fetchAll() {
        $resultSet = $this->select(function (Select $select) {
                    $select->order('id_parent ASC');
                });

        $entities = array();
        foreach ($resultSet as $row) { 
            $entity = new Resource();            
            $entity->setId($row->id);
            $entity->setIdparent($row->id_parent);
            $map= array(
                'id'=>$entity->getId(),
                'id_parent'=>$entity->getIdparent()
            ); 
            $entities[] = $map;
        }
        return $entities;
    }
    
    public function findId($resource){
        $idRosurce = 0;
        $resultSet = $this->select(function (Select $select) use ($resource){
                    $select->where(array('resource' => $resource));
                });
                $countField = $resultSet->count();
                
        if($countField===1){
            $idRosurce = (int) $resultSet->current()->id;
        }

        return $idRosurce;        
    }
}