<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */

namespace Cspermission\Model;
                  
use Zend\Db\Adapter\Adapter;
use Zend\Db\TableGateway\AbstractTableGateway;
use Zend\Db\Sql\Select as Select;
use Cspermission\Model\Entity\Roles as Roles;
                    
class RolesTable extends AbstractTableGateway{
   
    protected $table  = 'roles';
    
    public function __construct(Adapter $adapter) {
        $this->adapter = $adapter;
    }


    
    public function fetchAll() {
        $resultSet = $this->select(function (Select $select) {
                    $select->order('id_parent ASC');
                });

        $entities = array();
        foreach ($resultSet as $row) { 
            $entity = new Roles();            
            $entity->setId($row->id);
            $entity->setIdparent($row->id_parent);
            $map= array(
                'id'=>$entity->getId(),
                'id_parent'=>$entity->getIdparent()
            ); 
            $entities[] = $map;
        }
        return $entities;
    }
    
    public function isIdRole($id){
        $isRole = false;
        $resultSet = $this->select(function (Select $select) use ($id){
                    $select->where(array('id' => $id));
                });
                $countField = $resultSet->count();
                
        if($countField===1){
            $idRole = (int) $resultSet->current()->id;
            if($idRole) $isRole= true; 
        }

        return $isRole;         
    }
}        